version: "3.1"
services:
    redis:
      image: redis:6
      container_name: taiyokenki-redis
      environment:
        - TZ=Asia/Tokyo
      ports:
        - "6391:6379"

    postgresql:
      image: postgres:12.2-alpine
      container_name: taiyokenki-postgresql
      working_dir: /application
      volumes:
        - .:/application

      environment:
        - POSTGRES_DB=taiyokenki
        - POSTGRES_USER=taiyokenki
        - POSTGRES_PASSWORD=20187a63f0901ea878fc
        - TZ=Asia/Tokyo
        - PGTZ=Asia/Tokyo
      ports:
        - "3311:5432"
        
    php:
      build:
        context: ./
        dockerfile: php.Dockerfile
      container_name: taiyokenki-php
      user: ${UID}:${GID}
      links:
        - postgresql:postgresql
        - redis:redis
      ports:
        - "9011:9000"
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./docker:/home/www-data/
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    webserver:
      build:
        context: ./
        dockerfile: nginx.Dockerfile
      container_name: taiyokenki-webserver
      working_dir: /application
      links:
        - php:fpm
      environment:
        - FPM_HOST=fpm
        - FPM_PORT=9000
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./storage/logs/nginx/:/var/log/nginx
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
       - "8012:80"
       
    localstack:
      image: localstack/localstack-full
      container_name: localstack_demo
      ports:
        - '4566-4599:4566-4599'
        - '8055:8080'
      environment:
        - SERVICES=sqs
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
      volumes:
        - './.localstack:/tmp/localstack'
        - '/var/run/docker.sock:/var/run/docker.sock'

    firestore_emulator:
      image: mtlynch/firestore-emulator
      container_name: firestore_emulator
      environment:
        - FIRESTORE_PROJECT_ID=dummy-project-id
        - PORT=8200

    firebase:
      image: firebase:local
      hostname: "firebase-local"
      build:
        context: ../..
        dockerfile: docker/local/Dockerfile
      volumes:
        - ~/.config:/home/app/.config
        - ~/.bash_aliases:/home/app/.bash_aliases:ro
        - ~/.bashrc:/home/app/.bashrc:ro
        - ../../src:/home/app/src/
      ports:
          - 5000:5080
          - 5001:5001
          - 9005:9005
      tty: true    
